version: '3.8'

services:
  web:
    build: .
    command: sh -c "npx prisma generate && node server.js"
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://salsinmiedo_user:salsinmiedo_password@db:5432/salsinmiedo_db?schema=public
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: salsinmiedo_user
      POSTGRES_PASSWORD: salsinmiedo_password
      POSTGRES_DB: salsinmiedo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
